[store]
[store.primary]
connection = "postgresql://graph-node:let-me-in@postgres:5432/graph-node"
pool_size = 10

[chains]
ingestor = "default"

[chains.kmt]
shard = "primary"
provider = [
  { label = "kmt-rpc-0", url = "https://mainrpc.kalychain.io/rpc", features = ["archive", "traces"] }
]

[deployment]
[[deployment.rule]]
shard = "primary"
indexers = [ "default" ]

